### PR TITLE
Add attestation module from Plug

### LINKED ISSUE #75: Add attestation module
Add the attestation module from Plug into the CENNZnet runtime
https://github.com/plugblockchain/plug-blockchain/blob/1.0.0-rc1/prml/attestation/src/lib.rs

### PR DESCRIPTION
**Pull request by aliXsed**
Closes #75

### CODE REVIEW

**Review by cowboy-bebug — APPROVED** [review]
Yep looks good!

**Review by jordy25519 — APPROVED** [review]
LGTM

**Comment by jordy25519** [comment]
Need to sign the commit

**Comment by aliXsed** [comment]
> Need to sign the commit

Done.

**Pull request merged**
