### PR TITLE
Feature/benchmark develop updated

### PR DESCRIPTION
**Pull request by maochuanli**
Hi Jordy/Alex,

This PR will run the benchmark on top of the develop branch, and generate the benchmark files needed. Later on you are free to update the benchmark command lines in the Jenkinsfile.

### CODE REVIEW

**Comment by jordy25519** [comment]
thanks @maochuanli how is it triggered? how do we get the generated files?
would be good if we can:
- trigger the pipeline on demand e.g. by commenting `run @benchmark` or similar
- generated files are committed to the PR by a bot account

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark 2

**Comment by maochuanli** [comment]
> thanks @maochuanli how is it triggered? how do we get the generated files?
> would be good if we can:
> 
> * trigger the pipeline on demand e.g. by commenting `run @benchmark` or similar
> * generated files are committed to the PR by a bot account

trying to add PR comment - Mao

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
benchmark

**Comment by maochuanli** [comment]
close it and recreate the PR

**Pull request closed without merging**
