### PR TITLE
Migrate cennznet-testing module

### PR DESCRIPTION
**Pull request by cowboy-bebug**
~Doesn't build yet due to errors in `cennznet-runtime`.~

`cargo check -p cennznet-testing`
`cargo test -p cennznet-testing`
^ both run fine

### CODE REVIEW

**Comment by mzxyz** [comment]
Nice work,  looks like we need to solve `cennznet-runtime` first, then merge back all the changes and tesit this again?

**Review by mzxyz — APPROVED** [review]
Awesome work, LGTM

**Review by jordy25519 — APPROVED** [review]
LGTM

**Comment by mzxyz** [comment]
Just do it

**Pull request merged**
